queue: queue-a
jobSetId: job-set-1
count: 2
queuePriorityFactor: 10
jobs:
  - name: heavy_cpu_job
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: cpu-stress-burner
          imagePullPolicy: IfNotPresent
          image: containerstack/alpine-stress:latest
          command:
            - sh
          args:
            - -c
            - "stress --cpu 1 --timeout $(( (RANDOM % 120) + 100))s"
          resources:
            limits:
              memory: 128Mi
              cpu: 0.2
            requests:
              memory: 128Mi
              cpu: 0.2
